name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
            VUE_APP_BASE_URL: http://localhost:8080/
            # Doesnt matter because tests shouldn't hit the API server
            VUE_APP_API_BASE_URL: http://localhost:3030/
        with:
          start: npm run serve
          wait-on: http://localhost:8080/